### ISSUE TITLE
Image Taking

### ISSUE THREAD

**Issue by JSJ08** [NJIT-EmbeddedSystems/whiteboard-scanner-eraser#7]
Find a way to capture and store images for stitching

So far, we've found a PiCamera library where we can control shutter speed and image capture

Will have to touch base with stitching and UI(?) groups to come up with appropriate save location for stitching after figuring this out.

**Comment by JSJ08** [comment]
While scanning, the motor will have to stop to take still images. That should be taken into consideration when coding for the physical movement.

**Comment by JSJ08** [comment]
Updated physical.py with an added scan function that will stop the motor to take pictures.

**Comment by JSJ08** [comment]
Any image captured using camera.capture() will need a name like "xyz.jpg" in the brackets. We will have to come up with a naming system for the images taken.

**Comment by rooq** [comment]
> Any image captured using camera.capture() will need a name like "xyz.jpg" in the brackets. We will have to come up with a naming system for the images taken.

timestamp of when the image was taken should suffice
